-   repo: git://github.com/pre-commit/pre-commit-hooks.git
    sha: 6b1aa19425b35f8c34f43ada8f1045b028dc19a5
    hooks:
    -   id: autopep8-wrapper
        args:
        - --in-place
        - --aggressive
        - --aggressive
        - --max-line-length=131
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
        files: \.(jshintrc|json)$
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: flake8
        args:
        - --max-line-length=131
        - --ignore=E126,E128,E731
    -   id: pretty-format-json
        args:
        - --autofix
        - --indent
        - '4'
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: git://github.com/pre-commit/mirrors-jshint
    sha: 431358a85a3084cb86d731f2cd46490ec04f5c69
    hooks:
    -   id: jshint
        args:
        - --config=.jshintrc
